version: '3.8'

services:
  app:
    build: .
    image: ffmpeg-server
    container_name: ffmpeg-server
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
    volumes:
      - ./logs:/app/logs
      - ./.env:/.env